export default {
  SORT : "SORT",
  FETCH_POSTS: "FETCH_POSTS",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAIL: "FETCH_POSTS_FAIL",
  FETCH_SHOW_POSTS: "FETCH_SHOW_POSTS",
  FETCH_SHOW_POSTS_SUCCESS: "FETCH_SHOW_POSTS_SUCCESS",
  FETCH_SHOW_POSTS_FAIL: "FETCH_SHOW_POSTS_FAIL"
}